id: PE26119F9
initial_creation_type: input
source_metadata:
  title: Jamgön Kongtrul Lodrö Thaye Series
  language: pt
  description: Works by or about the great nineteenth century master Jamgön Kongtrul
    Lodrö Thaye ('jam mgon kong sprul blo gros mtha' yas, 1813–1899), one of the pioneers
    of the Rimé movement
  volume:
    648d44d9c435424dae2696008e0312ef:
      title: Advice to Lhawang Tashi
      parent: Advice
    c8f65517420d477da74e38a99a91e910:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    323d4a28fbc14b4f8ea2de9928cd1112:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    d1f93f964f0843ada877e324ec46d38c:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    c20221b387794ca49f7f5a4e588d8bf0:
      title: Prayer for Peace and Stability in Tibet
      parent: Aspiration Prayers
    30c4901df17d4a5b8ca9721df4b03029:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Aspiration Prayers
    a9d16e682ade44809f7d65ba86161810:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Biography
    f762903d78d14f95a539fdd89c123f37:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    5b80c9c791c2460fa17ac49052836367:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Biography
    47ea37b5afb14d069baa4bebde45bd93:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Calling the Guru From Afar
    05e03aae41fe43a58202f7f0277aa2a2:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Commentaries
    e55f6077144846ff94205d7d7f1497fc:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Empowerment Rites
    1c8cb33bb41c47bc8842958dedfa45c1:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Fire Offering
    b5733b6d448d44daa1e6e4ad9987c2e1:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Guru Rinpoche Prayers
    681a165f2b324dc0ac0ede4d5ccc2792:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Lineage Prayers
    7c579376e10e431eba3ceeee3dc24304:
      title: A Short Supplication to Tārā
      parent: Prayers
    e287075d8ea44a4897ef484eecac2ff0:
      title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse
        Chökyi Lodrö
      parent: Prayers
    bfac59daca95419aa92dfbb782d8d572:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    f5a6f3865b734809a2be177a4876943b:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Prayers
    0b11f224bb894be2b15df665b90fdef8:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      parent: Prayers
    a97386da6a2d4172a702be1c6284d67c:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Prayers
    96ef11b6f0f540678d1d1ffc5828bd6b:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Saving Lives
    7df275c80cb74bf28dd1c5532e6120f0:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Swift Rebirth Prayers
    45cc418b8ed14b908ac472d6f8bb74c3:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Tsok
    6e47e582584f4a709f08d93222c6afe5:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T23:32:21.220621'
last_modified_at: '2022-02-28T23:32:21.220624'
